### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ahmadniknezhad** [tatoliop/parallel-streaming-outlier-detection#3]
hello
thank you for your great work.
How can I access the dataset of this work?

**Comment by tatoliop** [comment]
Hello,
thank you for your kind words! The datasets that were tested along with the code are open and can be found here:

- [FC (55d)](http://kdd.ics.uci.edu)
- [TAO (3d)](http://www.pmel.noaa.gov)
- [STOCK (1d)](https://wrds-web.wharton.upenn.edu/wrds/)

You can also find more information for this repository [here](https://www.sciencedirect.com/science/article/pii/S0306437920300594)!

**Comment by ahmadniknezhad** [comment]
thank you a lot for your response. I am grateful for your help.
